name: Example
on:
  pull_request: null
  push:
    branches:
    - main
jobs:
  run:
    name: Run Example
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-18.04
          - macos-10.15
          - windows-2019
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: run bazel example (Elm)
      run: |
        bazelisk build //example:elm-api
        diff -r bazel-bin/example/elm example/elm
